---
title: "Data Collection"
format:
    html: 
        code-fold: true
---


{{< include overview.qmd >}}

{{< include methods.qmd >}}

# Code

In [ ]:
import requests
import pandas as pd

## WHO Data Collection

The WHO API provides access to a comprehensive database of global health indicators, covering various aspects of public health, including chronic disease prevalence, risk factors, and treatment coverage. Since querying the API requires specific indicator codes, the first step involved fetching the full list of indicators using the [WHO Indicator API Endpoint](https://ghoapi.azureedge.net/api/Indicator). The data was saved as `who_indicators_list.csv` for further filtering. 

Relevant indicators were identified by searching for keywords such as "blood," "pressure," "glucose," "diabetes," and "hypertension." These terms align with the project’s focus on chronic disease analysis. After filtering, key indicators related to BMI, hypertension, and diabetes were selected based on their relevance to the research objectives. This streamlined dataset enabled targeted data collection using the WHO API.

The selected indicators were programmatically fetched using Python’s `requests` library and saved as CSV files. Each file represents a specific health indicator, structured with consistent columns for easy integration and analysis. These files include data on average BMI, diabetes prevalence, and hypertension control rates across countries, demographic groups, and years, forming the foundation for the project’s subsequent data analysis and modeling efforts.

In [1]:
# WHO API main URL
base_url = "https://ghoapi.azureedge.net/api/Indicator"

# Request available indicators from WHO API
response = requests.get(base_url)

if response.status_code == 200:
    data = response.json()
    indicators = pd.DataFrame(data['value'])
    indicators.to_csv('../../data/raw-data/who_indicators_list.csv', index=False)
    print("WHO indicator list has been saved to who_indicators_list.csv")
else:
    print(f"Request failed, status code: {response.status_code}")

WHO indicator list has been saved to who_indicators_list.csv

### Contents of `who_indicators_list`
The `who_indicators_list.csv` file contains metadata about all available health indicators in the WHO database. Each row represents a specific health indicator, with the following key columns:

- **IndicatorCode**: The unique identifier required to query the specific dataset.

- **IndicatorName**: A descriptive label that provides details about what the indicator measures.

- **Language**: The language in which the indicator name is written. 

This dataset offers a broad overview of available health statistics, spanning diverse topics such as environmental health, chronic diseases, financial protection, and global epidemiology. It serves as the foundation for selecting the specific indicators relevant to this project. By filtering the data for keywords associated with chronic diseases and allowed me to filter and identify the most relevant indicators for my project.

In [5]:
# Load the CSV into a DataFrame
who_indicators_df = pd.read_csv('../../data/raw-data/who_indicators_list.csv')

# Display the first few rows to inspect the structure
who_indicators_df.head()

,IndicatorCode,IndicatorName,Language
0,EMFLIMITPOWERDENSITY900,Power density limit at 900 MHz (W/m^2),EN
1,EMFPOWERFREQUENCY,Power frequency (Hz),EN
2,FINPROTECTION_CATA_ESTIMATE_AVAILABLE,Availability of estimates on large health exp...,EN
3,HIV_0000000001,Estimated number of people (all ages) living w...,EN
4,FINPROTECTION_CATA_TOT_25_LEVEL_SH,Population with household spending on health g...,EN

After obtaining the full list of indicators, I filtered them based on specific keywords such as **"blood"**, **"pressure"**, **"glucose"**, **"diabetes"**, and **"hypertension"**. These keywords align with the chronic disease focus of this project. The filtering process was automated using pandas library.

In [6]:
# Filter the WHO indicators list for relevant keywords
keywords = ["blood", "pressure", "glucose", "diabetes", "hypertension"]
filtered_indicators = who_indicators_df[who_indicators_df['IndicatorName'].str.contains('|'.join(keywords), case=False, na=False)]

filtered_indicators

,IndicatorCode,IndicatorName,Language
232,LEAD_4,Percentage of the adults (15+ years) with bloo...,EN
237,LEAD_3,Percentage of the adults (15+ years) with bloo...,EN
267,NCD_CCS_DiabetesReg,Existence of a diabetes registry,EN
268,NCD_CCS_DiabetesTest,General availability of diabetes testing (by b...,EN
275,NCD_CCS_DiabPlan,Existence of operational policy/strategy/actio...,EN
281,LEAD_1,Percentage of the children under 15 years with...,EN
365,NCD_CCS_HbA1c,General availability of diabetes testing (by H...,EN
383,LEAD_2,Percentage of the children under 15 years with...,EN
469,NCD_CCS_diabtest,General availability of diabetes testing (by b...,EN
519,NCDMORT3070,Probability (%) of dying between age 30 and ex...,EN
523,NCD_GLUC_01,Mean fasting blood glucose (mmol/l) (age-stand...,EN
526,NCD_GLUC_02,Mean fasting blood glucose (mmol/l) (crude est...,EN
527,NCD_GLUC_03,Raised fasting blood glucose (>= 7.0 mmol/L) (...,EN
614,NCD_GLUC_04,Raised fasting blood glucose (>=7.0 mmol/L) (a...,EN
789,SA_0000001421,"Age-standardized DALYs, diabetes mellitus, per...",EN
957,SA_0000001440,"Age-standardized death rates, diabetes mellitu...",EN
1106,SA_0000001520,Legal blood alcohol concentration (BAC) limits,EN
1107,SA_0000001520_ARCHIVED,Legal blood alcohol concentration (BAC) limits,EN
1618,UHC_NCD_FPG,Mean fasting plasma glucose,EN
1629,UHC_NCD_NONELEVBP,Prevalence of non-elevated blood pressure (%),EN
1821,RS_207,Blood Alcohol Concentration (BAC) limit for dr...,EN
2029,BP_04,Raised blood pressure (SBP>=140 OR DBP>=90) (a...,EN
2032,BP_03,Raised blood pressure (SBP>=140 OR DBP>=90) (c...,EN
2038,BP_05,Mean systolic blood pressure (crude estimate),EN
2039,BP_06,Mean systolic blood pressure (age-standardized...,EN
2317,NCD_CCS_BPmsmt,General availability of blood pressure measure...,EN
2323,NCD_HYP_PREVALENCE_A,Prevalence of hypertension among adults aged 3...,EN
2329,NCD_HYP_PREVALENCE_C,Prevalence of hypertension among adults aged 3...,EN
2340,NCD_CCS_BP_SVY,"Has conducted a recent, national adult risk fa...",EN
2390,AMR_INFECT_ECOLI,Proportion of bloodstream infection due to Esc...,EN
2401,NCD_HYP_CONTROL_C,Effective hypertension treatment coverage amon...,EN
2428,NCD_HYP_TREATMENT_A,Hypertension treatment coverage among adults a...,EN
2541,NCD_HYP_DIAGNOSIS_C,Hypertension diagnosis coverage among adults a...,EN
2581,NCD_CCS_DIAB_SVY,"Has conducted a recent, national adult risk fa...",EN
2629,NCD_CCS_DIAB_TARGET,Existence of a national target on diabetes,EN
2693,NCD_DIABETES_TREATMENT_AGESTD,"Diabetes treatment coverage, age-standardized",EN
2715,NCD_DIABETES_PREVALENCE_CRUDE,"Prevalence of diabetes, crude",EN
2725,NCD_CCS_urine_strips_gluc_ketone,General availability of urine strips for gluco...,EN
2749,NCD_DIABETES_TREATMENT_CRUDE,"Diabetes treatment coverage, crude",EN
2778,NCD_HYP_DIAGNOSIS_A,Hypertension diagnosis coverage among adults a...,EN
2800,NCD_HYP_CONTROL_A,Effective hypertension treatment coverage amon...,EN
2804,AMR_INFECT_MRSA,Proportion of bloodstream infection due to met...,EN
2855,NCD_HYP_TREATMENT_C,Hypertension treatment coverage among adults a...,EN
2876,NCD_CCS_BP_TARGET,Existence of a national target on blood pressu...,EN
2883,NCD_DIABETES_PREVALENCE_AGESTD,"Prevalence of diabetes, age-standardized",EN
2907,NCD_CCS_DIAB_GUIDE,Existence of evidence-based national guideline...,EN
2909,PRISON_D4_DIABETES_DIAG_TOT,In-prison diabetes mellitus diagnosis (number ...,EN

This step narrowed the list to a manageable subset of indicators directly related to the research objectives. The selected indicators include:

- BMI:

    - `NCD_BMI_MEAN`: Mean Body Mass Index across countries, reflecting obesity trends.

- Hypertension:
    - `NCD_HYP_PREVALENCE_A`: Prevalence of hypertension among adults.
    - `NCD_HYP_CONTROL_A`: Hypertension control rates.
    - `NCD_HYP_TREATMENT_A`: Hypertension treatment rates.

- Diabetes and Blood Glucose:
    - `NCD_DIABETES_PREVALENCE_CRUDE`: Crude diabetes prevalence.
    - `NCD_DIABETES_PREVALENCE_AGESTD`: Age-standardized diabetes prevalence.
    - `NCD_GLUC_01` and `NCD_GLUC_02`: Fasting blood glucose levels.

These indicators were chosen because they provide quantitative measures of chronic disease prevalence, risk factors, and management strategies, making them essential for understanding global health patterns.

In [2]:
# WHO API request function
def fetch_who_data(indicator, output_file):
    url = f"https://ghoapi.azureedge.net/api/{indicator}"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        # Extract relevant data fields
        df = pd.DataFrame(data['value'])
        df.to_csv(f'../../data/raw-data/{output_file}.csv', index=False)
        print(f"{output_file}.csv Data saved successfully！")
    else:
        print(f"Request failed, status code: {response.status_code}")

# Get blood pressure related data
fetch_who_data("NCD_BMI_MEAN", "who_bmi_data")
fetch_who_data("NCD_HYP_PREVALENCE_A", "who_hypertension_prevalence")
fetch_who_data("NCD_HYP_CONTROL_A", "who_hypertension_control")
fetch_who_data("NCD_HYP_TREATMENT_A", "who_hypertension_treatment")

# Get diabetes related data
fetch_who_data("NCD_BMI_MEAN", "who_bmi_data")
fetch_who_data("NCD_GLUC_01", "who_blood_glucose_age_std")
fetch_who_data("NCD_GLUC_02", "who_blood_glucose_crude")
fetch_who_data("NCD_DIABETES_PREVALENCE_CRUDE", "who_diabetes_prevalence_crude")
fetch_who_data("NCD_DIABETES_PREVALENCE_AGESTD", "who_diabetes_prevalence_age_std")

who_bmi_data.csv Data saved successfully！
who_hypertension_prevalence.csv Data saved successfully！
who_hypertension_control.csv Data saved successfully！
who_hypertension_treatment.csv Data saved successfully！
who_bmi_data.csv Data saved successfully！
who_blood_glucose_age_std.csv Data saved successfully！
who_blood_glucose_crude.csv Data saved successfully！
who_diabetes_prevalence_crude.csv Data saved successfully！
who_diabetes_prevalence_age_std.csv Data saved successfully！

The raw data collected from the WHO API is stored in CSV format. Each file represents a specific health indicator (e.g., BMI, diabetes prevalence, hypertension control) and contains consistent column structures across all datasets. Data can be found from [WHO Data](https://drive.google.com/drive/folders/1puoOCSccRjK5w9MeDEmJUJ4dbnpPkFhC?usp=sharing).

Each CSV file corresponds to a specific health indicator :

1. **`who_bmi_data.csv`**:  
   - Mean Body Mass Index by country, year, and demographic group.

2. **`who_hypertension_prevalence.csv`**:  
   - Hypertension prevalence by geographic and demographic dimensions.

3. **`who_hypertension_control.csv`**:  
   - Effective hypertension treatment coverage, indicating the percentage of the population receiving adequate treatment.

4. **`who_hypertension_treatment.csv`**:  
   - Hypertension treatment coverage, reflecting the proportion of the population undergoing hypertension treatment.

5. **`who_diabetes_prevalence_crude.csv`**:  
   - Crude diabetes prevalence, providing an unadjusted rate of diabetes occurrence.

6. **`who_diabetes_prevalence_age_std.csv`**:  
   - Age-standardized diabetes prevalence, adjusted for age distribution differences.

7. **`who_blood_glucose_age_std.csv`**:  
   - Mean fasting blood glucose levels, age-standardized, representing the average glucose concentration among the population.

8. **`who_blood_glucose_crude.csv`**:  
   - Mean fasting blood glucose levels, crude estimates, reflecting the average glucose concentration without adjustments.

### Columns in the WHO Dataset

The WHO datasets contain a range of metadata, demographic details, numerical data, and additional context-specific information. Here’s a breakdown of the key columns found across the collected CSV files:  

#### **1. Metadata Columns:**  
- **`Id`**: Unique identifier for each observation (Integer).  
- **`IndicatorCode`**: Unique code representing the health indicator (String).  
- **`SpatialDimType` & `SpatialDim`**: Geographic classification, indicating country or region (String).  
- **`ParentLocationCode` & `ParentLocation`**: Higher-level geographic grouping for regional aggregation (String).  
- **`TimeDimType` & `TimeDim`**: Temporal classification indicating the year or time period of the data (String & Integer).  

#### **2. Demographic Dimensions:**  
- **`Dim1Type` & `Dim1`**: Primary demographic factor (e.g., gender, age group) (String).  
- **`Dim2Type` & `Dim2`**: Secondary demographic category, if applicable (String).  
- **`Dim3Type` & `Dim3`**: Tertiary demographic category, for further breakdown (String).  

#### **3. Data Source:**  
- **`DataSourceDimType` & `DataSourceDim`**: Information about the data source or collection method (String).  

#### **4. Numerical Data Columns:**  
- **`Value`**: Recorded health statistic, often provided as a descriptive range (String).  
- **`NumericValue`**: Central numerical value representing the indicator's exact measurement (Float).  
- **`Low` & `High`**: Confidence interval bounds indicating the reliability of the reported statistic (Float).  

#### **5. Additional Columns:**  
- **`Comments`**: Additional notes or remarks about the data entry (String).  
- **`Date`**: Date when the data was last updated (Datetime).  
- **`TimeDimensionBegin` & `TimeDimensionEnd`**: Start and end dates of the observation period, if applicable (Datetime).  

These columns provide essential context and structure, supporting a comprehensive understanding of global health indicators, demographic patterns, and trends crucial for the analysis of chronic disease prevalence.

{{< include closing.qmd >}}